---
language: python
python: "2.7"
services:
  - docker
env:
  global:
    - ANSIBLE_HOST_KEY_CHECKING="False"
install:
  - pip install ansible docker-py
  - ansible --version
  - ansible-galaxy install -r tests/requirements.yml -p tests/roles/
script:
  - ansible-playbook --syntax-check -i tests/inventory tests/test.yml
  - ansible-playbook -i tests/inventory tests/test.yml
notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
