---
# installing gradle

- name: Gradle | Download gradle
  get_url:
    url: "https://services.gradle.org/distributions/gradle-{{gradle_version}}-all.zip"
    dest: "/tmp/gradle-{{gradle_version}}-all.zip"

- name: Gradle | apt-get update
  apt: update_cache=yes
  when: ansible_os_family == 'Debian'

- name: Gradle | Install unzip
  apt: pkg=unzip state=latest
  when: ansible_os_family == 'Debian'

- name: Gradle | Install unzip
  yum: name=unzip state=latest
  when: ansible_os_family == 'RedHat'

- name: Gradle | Unpack the compressed Gradle
  unarchive:
    src: /tmp/gradle-{{gradle_version}}-all.zip
    dest: /usr/local
    remote_src: yes

- name: Grade | Rename Gradle folder
  command: mv /usr/local/gradle-{{gradle_version}} /usr/local/gradle

- name: Gradle | Set the permissions on the Gradle binary
  file:
    path: "/usr/local/gradle/bin"
    state: directory
    mode: 0755
    recurse: yes

- name: Install libselinux-python package for 'copy' task
  yum:
    name: libselinux-python
    state: present
  when: ansible_os_family == "RedHat"

- name: Gradle | Add the Gradle binary to the system path (/etc/profile.d/gradle.sh)
  copy:
    dest: /etc/profile.d/gradle.sh
    content: |
      export GRADLE_HOME=/usr/local/gradle
      export PATH=$PATH:$GRADLE_HOME/bin
